import React, { useEffect, useState } from 'react';
import { Target, TrendingUp, Award, Zap, ChevronRight, Loader2, Sparkles, ArrowRight, CheckCircle2, Star, List, Info, Filter, Clock } from 'lucide-react';
import { saveTodaysProblems, clearTodaysProblems, hasTodaysProblems, getTodayKey, areAllProblemsComplete } from '../services/problemStorage';

export default function Dashboard({ setCurrentView, setActiveProblem, dailyProblems, setDailyProblems, allProblems, setAllProblems, userProfile, authToken }) {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [generateError, setGenerateError] = useState(null);

    // Map level to default difficulty
    const levelToDifficulty = { Beginner: 'Easy', Intermediate: 'Medium', Advanced: 'Hard' };

    // Generator state — pre-filled from profile
    const [problemCount, setProblemCount] = useState(userProfile?.profile?.problemsPerDay || 5);
    const [difficulty, setDifficulty] = useState(levelToDifficulty[userProfile?.profile?.level] || 'Medium');
    const [targetTopic, setTargetTopic] = useState('Dynamic Programming');
    const [isGenerating, setIsGenerating] = useState(false);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

    // Derived: how many of today's problems are done
    const completedCount = dailyProblems.filter(p => p.isCompleted).length;
    const allDone = areAllProblemsComplete(dailyProblems);
    const hasProblems = dailyProblems.length > 0;
    const progressPercent = hasProblems ? (completedCount / dailyProblems.length) * 100 : 0;

    useEffect(() => {
        async function fetchDashboard() {
            try {
                const res = await fetch('http://localhost:3000/api/dashboard');
                if (res.ok) {
                    setData(await res.json());
                }
            } catch (err) {
                console.error("Failed to load dashboard data", err);
            } finally {
                setLoading(false);
            }
        }
        fetchDashboard();
    }, []);

    const handleGenerate = async () => {
        setIsGenerating(true);
        setGenerateError(null);
        try {
            const res = await fetch('http://localhost:3000/api/problems/generateBatch', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${authToken}`
                },
                body: JSON.stringify({ topic: targetTopic, difficulty, count: problemCount })
            });
            if (res.ok) {
                const generatedBatch = await res.json();
                if (Array.isArray(generatedBatch) && generatedBatch.length > 0) {
                    const today = getTodayKey();
                    const taggedBatch = generatedBatch.map(p => ({ ...p, generatedDate: today }));
                    saveTodaysProblems(taggedBatch);
                    setDailyProblems(taggedBatch);
                    setAllProblems(prev => {
                        const filtered = prev.filter(p => p.generatedDate !== today);
                        return [...taggedBatch, ...filtered];
                    });
                }
            } else {
                const errData = await res.json().catch(() => ({}));
                setGenerateError(errData.message || 'Failed to generate problems. Please try again.');
            }
        } catch (err) {
            setGenerateError('Network error. Please check your connection.');
        } finally {
            setIsGenerating(false);
        }
    };

    useEffect(() => {
        if (!hasAutoGenerated && dailyProblems.length === 0 && !hasTodaysProblems() && userProfile && !loading) {
            setHasAutoGenerated(true);
            handleGenerate();
        } else if (!hasAutoGenerated) {
            setHasAutoGenerated(true);
        }
    }, [loading, hasAutoGenerated, dailyProblems.length]);

    if (loading || !data) {
        return (
            <div className="flex-1 overflow-y-auto bg-[#F8F9FB] p-8 flex items-center justify-center">
                <div className="flex flex-col items-center">
                    <Loader2 className="w-8 h-8 text-orange-500 animate-spin mb-4" />
                    <div className="text-gray-400 font-medium">Preparing your workspace...</div>
                </div>
            </div>
        );
    }

    const { userStats } = data;

    return (
        <div className="flex-1 overflow-y-auto bg-[#FBFBFC] px-8 py-12 relative font-sans">
            <div className="max-w-5xl mx-auto space-y-12">
                
                {/* Generation Engine - Unified with Workspace */}
                <div className="bg-white rounded-md border border-gray-100 shadow-[0_8px_30px_rgba(0,0,0,0.04)] overflow-hidden">
                    <div className="p-8 border-b border-gray-50 flex flex-wrap lg:flex-nowrap items-center gap-10">
                        <div className="flex items-center gap-5 border-r border-gray-100/60 pr-10">
                            <div className="w-12 h-12 bg-indigo-600 rounded-md flex items-center justify-center shadow-lg shadow-indigo-500/20">
                                <Sparkles className="w-6 h-6 text-white" />
                            </div>
                            <div>
                                <h1 className="text-[18px] font-black text-[#1E293B] uppercase tracking-wider">Workspace Generator</h1>
                                <p className="text-[#94A3B8] text-[10px] font-bold uppercase tracking-widest mt-0.5">Prepare Today's Batch</p>
                            </div>
                        </div>

                        <div className="flex-1 flex flex-wrap lg:flex-nowrap items-center gap-8 px-2">
                            <div className="flex items-center gap-6 min-w-[200px]">
                                <div className="flex flex-col gap-0.5">
                                    <label className="text-[9px] font-black text-[#94A3B8] uppercase tracking-[0.2em]">Batch Size</label>
                                    <span className="text-[#1E293B] text-[12px] font-black">{problemCount}</span>
                                </div>
                                <input
                                    type="range"
                                    min="1"
                                    max="10"
                                    value={problemCount}
                                    onChange={(e) => setProblemCount(e.target.value)}
                                    className="flex-1 h-1 bg-gray-100 rounded-full appearance-none cursor-pointer accent-indigo-600 focus:outline-none"
                                />
                            </div>

                            <div className="flex items-center gap-2">
                                {['Easy', 'Medium', 'Hard', 'Expert'].map(level => (
                                    <button
                                        key={level}
                                        onClick={() => setDifficulty(level)}
                                        className={`py-2 px-4 rounded-md text-[10px] font-black transition-all border tracking-[0.1em] uppercase ${difficulty === level
                                            ? 'bg-[#1E293B] text-white border-[#1E293B] shadow-md'
                                            : 'bg-gray-50/50 text-[#64748B] border-transparent hover:border-gray-200 hover:bg-white'
                                            }`}
                                    >
                                        {level}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <button
                            onClick={handleGenerate}
                            disabled={isGenerating}
                            className="bg-indigo-600 hover:bg-indigo-700 text-white h-12 px-10 rounded-md font-black text-[11px] uppercase tracking-[0.2em] transition-all flex items-center gap-3 shadow-xl shadow-indigo-500/10 active:scale-95 disabled:opacity-50"
                        >
                            {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <><Sparkles className="w-4 h-4" /> Add Problems</>}
                        </button>
                    </div>

                    {/* Active Solving List */}
                    <div className="p-8">
                        <div className="flex items-center justify-between mb-8">
                            <h2 className="text-[15px] font-black text-[#1E293B] uppercase tracking-[0.2em]">Today's Pending Tasks</h2>
                            <div className="flex items-center gap-3">
                                <div className="text-[11px] font-black text-[#94A3B8] uppercase tracking-widest">{completedCount}/{dailyProblems.length} Collected</div>
                                <div className="w-32 h-1.5 bg-gray-100 rounded-full overflow-hidden">
                                    <div className="h-full bg-indigo-500 transition-all duration-1000" style={{ width: `${progressPercent}%` }} />
                                </div>
                            </div>
                        </div>

                        {dailyProblems.filter(p => !p.isCompleted).length === 0 ? (
                            <div className="py-20 flex flex-col items-center justify-center text-center bg-gray-50/30 rounded-md border border-dashed border-gray-200">
                                <CheckCircle2 className="w-10 h-10 text-emerald-400 mb-4" />
                                <h3 className="text-[14px] font-black text-[#1E293B] uppercase tracking-widest">Workspace Clear</h3>
                                <p className="text-[#94A3B8] text-[11px] mt-2 max-w-[240px]">You've completed all tasks or the queue is currently empty.</p>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                {dailyProblems.filter(p => !p.isCompleted).map((p, idx) => (
                                    <div
                                        key={p.id || idx}
                                        onClick={() => {
                                            setActiveProblem(p);
                                            setCurrentView('Practice');
                                        }}
                                        className="group bg-white border border-gray-100 rounded-md p-5 flex items-center justify-between transition-all hover:border-indigo-100 hover:shadow-[0_8px_20px_rgba(0,0,0,0.03)] cursor-pointer"
                                    >
                                        <div className="flex items-center gap-6">
                                            <div className="w-10 h-10 bg-indigo-50 text-indigo-600 rounded-md flex items-center justify-center text-[14px] font-black group-hover:bg-indigo-600 group-hover:text-white transition-all">
                                                {String(idx + 1).padStart(2, '0')}
                                            </div>
                                            <div>
                                                <h3 className="text-[16px] font-black text-[#1E293B] group-hover:text-indigo-600 transition-colors line-clamp-1">{p.title}</h3>
                                                <div className="flex items-center gap-4 mt-1.5">
                                                    <span className={`text-[8px] font-black px-2 py-0.5 rounded-sm uppercase tracking-wider ${
                                                        p.difficulty === 'Easy' ? 'bg-emerald-50 text-emerald-600' :
                                                        p.difficulty === 'Medium' ? 'bg-amber-50 text-amber-600' :
                                                        p.difficulty === 'Hard' ? 'bg-rose-50 text-rose-600' : 'bg-purple-50 text-purple-600'
                                                    }`}>
                                                        {p.difficulty}
                                                    </span>
                                                    <span className="text-[#94A3B8] text-[10px] font-black uppercase tracking-widest flex items-center gap-1.5">
                                                        <Clock className="w-3 h-3" /> {p.timeEstimate}
                                                    </span>
                                                    <span className="text-[#94A3B8] text-[10px] font-black uppercase tracking-widest">• {p.topic}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <ChevronRight className="w-5 h-5 text-gray-200 group-hover:text-indigo-500 transition-all transform group-hover:translate-x-1" />
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

                {/* Solved Problems Collection */}
                <div className="bg-white rounded-md border border-gray-100 shadow-sm overflow-hidden">
                    <div className="px-8 py-8 border-b border-gray-50 flex items-center justify-between bg-[#FBFBFC]/50">
                        <div>
                            <h2 className="text-[15px] font-black text-[#1E293B] uppercase tracking-[0.2em]">Verified Solutions</h2>
                            <p className="text-[#94A3B8] text-[10px] font-bold uppercase tracking-widest mt-1">Collection of AI generated challenges mastered</p>
                        </div>
                        <div className="bg-emerald-50 text-emerald-600 px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest">
                            {allProblems.filter(p => p.isCompleted).length} Accomplished
                        </div>
                    </div>

                    <div className="overflow-x-auto">
                        <table className="w-full text-left">
                            <thead className="bg-[#FBFBFC]">
                                <tr>
                                    <th className="px-8 py-4 text-[#94A3B8] text-[10px] font-black uppercase tracking-[0.2em]">ID</th>
                                    <th className="px-8 py-4 text-[#94A3B8] text-[10px] font-black uppercase tracking-[0.2em]">Challenge</th>
                                    <th className="px-8 py-4 text-[#94A3B8] text-[10px] font-black uppercase tracking-[0.2em]">Rating</th>
                                    <th className="px-8 py-4 text-[#94A3B8] text-[10px] font-black uppercase tracking-[0.2em]">Domain</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-50">
                                {allProblems.filter(p => p.isCompleted).map((problem, idx) => (
                                    <tr
                                        key={problem.id || idx}
                                        onClick={() => {
                                            setActiveProblem(problem);
                                            setCurrentView('Practice');
                                        }}
                                        className="hover:bg-gray-50 transition-colors cursor-pointer group"
                                    >
                                        <td className="px-8 py-6 font-black text-[#CBD5E1] text-[11px] tabular-nums">{String(idx + 1).padStart(3, '0')}</td>
                                        <td className="px-8 py-6">
                                            <div className="text-[#1E293B] text-[14px] font-black group-hover:text-indigo-600 transition-colors">
                                                {problem.title}
                                            </div>
                                            <div className="text-[#94A3B8] text-[9px] font-bold uppercase tracking-widest mt-1 opacity-60">{problem.generatedDate || 'Archive Record'}</div>
                                        </td>
                                        <td className="px-8 py-6">
                                            <span className={`px-2 py-0.5 rounded-sm text-[8px] font-black uppercase tracking-widest ${
                                                problem.difficulty === 'Easy' ? 'bg-emerald-50 text-emerald-500' :
                                                problem.difficulty === 'Medium' ? 'bg-amber-50 text-amber-500' :
                                                'bg-rose-50 text-rose-500'
                                            }`}>
                                                {problem.difficulty}
                                            </span>
                                        </td>
                                        <td className="px-8 py-6 text-[#64748B] text-[10px] font-black uppercase tracking-widest opacity-80">{problem.topic}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>

                        {allProblems.filter(p => p.isCompleted).length === 0 && (
                            <div className="py-24 text-center">
                                <Award className="w-12 h-12 text-gray-100 mx-auto mb-4" />
                                <div className="text-[#94A3B8] font-black text-[12px] uppercase tracking-[0.3em] opacity-40">No Solutions Captured Yet</div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
